### ISSUE TITLE
Learn from other MUD projects

### ISSUE THREAD

**Issue by dernewt** [RubyNova/SharperUniverse#17]
What specifically are the project goals?
How will it differentiate from some of the other csharp MUD efforts out there?
What can we learn from the other codebases?

A quick search limited to csharp (if this is a path you want to take we should look harder):

Engine,
https://github.com/WheelMud/WheelMUD

Engine, netcore, network infrastructure:
https://github.com/FacticiusVir/MercuryCore

engine+game
https://github.com/Blecki/RMUD

Good starting point on the history of the many MUD engines:
https://en.wikipedia.org/wiki/MUD

**Comment by RubyNova** [comment]
As of right now, the goal is to (primarily) be a game library/engine that can be used alongside something such as the yellowbook. I get a lot of people brand new to C# asking me for help with using Unity, and it's kind of frustrating to constantly tell them to, well, stop and learn the language first. I'd like this library to help be a sort of scalable replacement for learning basic games design, OOP and ECS. Unity is a bad learning platform for all three at once on top of the language.

It's also to aid a couple of friends of mine in learning games development from a theory perspective.

I'll take a look at those links you sent when I have the time, thanks.
